
if __name__ == "__main__":
    import sys
    import numpy as np
    import pandas as pd
    from pathlib import Path
    # Adjust paths according to the project structure
    sys.path.append(str(Path(__file__).resolve().parents[1]))
    from engine.main import Model
    from engine.patterns import Patterns
    from pysindy import STLSQ


    # ==========================================
    # PHASE 1: SYNTHETIC DATA GENERATION
    # We create a simple system: Population growing at a 10% rate
    # Real equation: dx/dt = 0.1 * population
    # ==========================================
    print("\n1. Generating synthetic data (Exponential growth)...")
    time_step = np.linspace(0, 10, 100)
    # population = 100 * e^(0.1 * t)
    population_data = 100 * np.exp(0.1 * time_step) 
    
    data = pd.DataFrame({
        "population": population_data
    })

    # ==========================================
    # PHASE 2: PATTERN DISCOVERY (SINDy)
    # ==========================================
    print("\n2. Run SINDy to discover the hidden equation...")
    model = Model()
    
    # Initialize the stock explicitly so SINDy can find it
    model.stock("population", initial_value=100.0)
    
    patterns = Patterns(model)
    
    # Use a time_step that matches the generated data
    dt = time_step[1] - time_step[0]
    # Lower the threshold to 0.01 so it doesn't kill the 0.1 coefficient
    optimizer = STLSQ(threshold=0.01, max_iter=50)

    # Pass the custom optimizer to fit_sindy
    result = patterns.fit_sindy(
        data, 
        time_step=dt, 
        optimizer=optimizer,
        epsilon=1e-4 
    )
    
    if isinstance(result, str):
        print(f"SINDy failed or was rejected: {result}")
        sys.exit()
    else:
        print("Equations injected into the model.")

    # ==========================================
    # PHASE 3: FORWARD SIMULATION
    # ==========================================
    print("\n3. Building and simulating the system (Forward Pass)...")
    state = model.build()
    
    # Simulate 5 steps
    steps = 5
    history = state.simulate(steps=steps)
    
    print("\nSimulation History (Population):")
    # Assuming history returns a dict or similar with the values
    for i in range(steps):
        # Access the real value inside the Element (Adjust according to your history format)
        value = history["population"][i].value if hasattr(history["population"][i], 'value') else history["population"][i]
        print(f" Step {i}: {value:.4f}")

    # ==========================================
    # PHASE 4: AUTOMATIC DIFFERENTIATION (BACKWARD)
    # The ultimate test for your Element class!
    # ==========================================
    print("\n4. Testing Autograd on the equations generated by SINDy...")
    
    # Grab the final Element object of the population
    final_state_element = history["population"][-1] 
    
    # Execute backpropagation from the end of the simulation
    final_state_element.backprop()
    
    print("Backpropagation completed. Computational graph is intact.")
    
    # Look for the coefficient SINDy created to check its gradient
    # (Sensitivity: How would a change in the coefficient affect the final result?)
    print("\nSensitivity of the discovered coefficients:")
    coefficient_found = False
    
    # Traverse the computational graph or the model registry looking for the coefficient
    # Assume model.auxiliary_variables exists; if not, look in the flows
    if hasattr(model, 'auxiliary_variables'):
        for name, aux_var in model.auxiliary_variables.items():
            if "coefficient" in name:
                coefficient_found = True
                print(f" -> Coefficient: '{name}'")
                print(f"    Value: {aux_var.value.value}")
                print(f"    Gradient: {aux_var.gradient}")
    
    if not coefficient_found:
        print(" (Note: Adapt the search for 'auxiliary_variables' according to the exact structure of your Model to print their gradients).")

    print("\n--- TEST FINISHED SUCCESSFULLY ---")

